name: Secrets and Variables Exercise

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  production-job:
    name: Run Production Job
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Print Production Environment Variable
        run: |
          echo "The current environment is: ${{ vars.MY_ENVIRONMENT }}"

  development-job:
    name: Run Development Job
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Print Development Environment Variable
        run: |
          echo "The current environment is: ${{ vars.MY_ENVIRONMENT }}"

  secrets-job:
    name: Run Secrets Job
    runs-on: ubuntu-latest

    steps:
      - name: Securely Use Repository Secret
        env:
          DEMO_USER: ${{ secrets.JB_DEMO_USER }}
        run: |
          echo "The demo user is: $DEMO_USER"